apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogue-db-dev
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: craftista:catalogue-db-dev-stage
spec:
  project: craftista
  source:
    repoURL: https://github.com/Mohamedgh01/microservice-helmcharts-gitops-project
    targetRevision: main
    path: service-charts/catalogue-db
    plugin:
      name: argocd-vault-plugin
      env:
        VAULT_ADDR: http://vault.vault.svc.cluster.local:8200  # ClusterIP accessible depuis le cluster
        VAULT_ROLE: argocd-role
        VAULT_SKIP_VERIFY: "true"  # à mettre "false" si certificat valide
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

