apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogue-db-staging
  namespace: argocd
spec:
  project: craftista
  source:
    repoURL: https://github.com/Mohamedgh01/microservice-helmcharts-gitops-projects
    targetRevision: main
    path: service-charts/catalogue-db
    plugin:
      name: argocd-vault-plugin
    helm:
      valueFiles:
        - /env/staging/catalogue-db/catalogue-db-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
