apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: voting-warehouse
  namespace: craftista
spec:
  freightCreationPolicy: Automatic
  interval: 1440m
  subscriptions:
    - image:
        repoURL: docker.io/mohamedgharbii/voting
        imageSelectionStrategy: SemVer
        discoveryLimit: 20
